[tool.poetry]
name = "granular-engine"
version = "v0.2.24"
description = "Experiment tracking for GeoSpatial Machine Learning on GeoEngine"
authors = ["Sagar Verma <sagar@granular.ai>"]
license = "MIT"
readme = "README.rst"
packages = [{include = "engine"}]
classifiers = [
    'Intended Audience :: Developers',
    'License :: OSI Approved :: MIT License',
    'Natural Language :: English',
    'Programming Language :: Python :: 3.7',
    'Programming Language :: Python :: 3.8',
    'Programming Language :: Python :: 3.9',
    'Programming Language :: Python :: 3.10',
]
repository='https://github.com/granularai/engine'


[tool.poetry.scripts]
engine = 'engine.cli:cli'

[tool.poetry.dependencies]
python = "^3.7.0"
yacs = "^0.1.8"
appdirs = "^1.4.4"
tabulate = "^0.9.0"
click = "^8.1.3"
keyrings-alt = "^4.2.0"
keyring = "^23.11.0"
passlib = "^1.7.4"
inquirerpy = "^0.3.4"
colorama = "^0.4.6"
yapf = "^0.33.0"
addict = "^2.4.0"

[tool.poetry.dev-dependencies]
pip = "^21.1.3"
beautifulsoup4 = "^4.10.0"
bump2version = "^1.0.1"
watchdog = "^2.1.3"
flake8 = "^3.9.2"
tox = "^3.24.0"
coverage = "^5.5"
Sphinx = "^4.1.1"
twine = "^3.4.1"
pytest = "^6.2.4"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

