[tool.poetry]
name = "alexdlbrain4"
version = "0.1.1"
description = ""
authors = ["Alex <afedorov2@gsu.edu>", "Linlin Lu <pku600gt@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.8"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
include = ["alex_build_v01.def"]