[tool.poetry]
name = "dhint"
version = "0.0.9"
description = ""
authors = ["Daniel Arantes <arantesdv@me.com>"]

[tool.poetry.dependencies]
python = "^3.9"
Unidecode = "^1.3.6"
typing-extensions = "^4.6.2"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
