[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "triclustering"
version = "2023.05.31.2"
authors = [
  { name="Dhiraj Bag", email="dhirajbag.db@gmail.com" }
]
description = "Triclustering and association rule mining using Suffix Forest and Frequent Closed Itemset based algorithm."
readme = "README.md"
requires-python = ">=3.10"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]
dependencies = [
  "pandas",
  "pydot",
]

[project.urls]
"Homepage" = "https://github.com/dhirajbag/triclustering-using-suffix_forest"
"Bug Tracker" = "https://github.com/dhirajbag/triclustering-using-suffix_forest/issues"