[project]
name = "reddit_photo_aggregator"
version = "1.0.3"
authors = [
  { name="hamolicious", email="hamolicious@outlook.com" },
]
description = "A library to scrape subreddits for images"
readme = "README.md"
requires-python = ">=3.11"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]
dependencies = [
	"beautifulsoup4==4.12.2",
	"requests==2.31.0",
	"bs4==0.0.1"
]

[project.urls]
"Homepage" = "https://github.com/hamolicious/Reddit-Photo-Aggregator"
"Bug Tracker" = "https://github.com/hamolicious/Reddit-Photo-Aggregator/issues"

[build-system]
requires = [
	"setuptools>=61.0",
]
build-backend = "setuptools.build_meta"
