
[build-system]
requires = ["setuptools>=61.0.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "quao"
version = "0.1.12"
description = "Quao Library supporting Quao Platform for Quantum Computing"
readme = "README.md"
authors = [{ name = "CITYNOW Co. Ltd. ", email = "corp@citynow.vn" }]
license = { file = "LICENSE" }
classifiers = [
    "License :: OSI Approved :: MIT License",
    "Programming Language :: Python",
    "Programming Language :: Python :: 3",
]
keywords = ["quao", "quantum"]
dependencies = [
    "qiskit==0.43.0",
    "qiskit_ibm_runtime==0.10.0",
    "qiskit-ibm-provider==0.6.0",
    "amazon-braket-sdk==1.38.1",
    "matplotlib==3.7.1",
    "pylatexenc==2.10",
    "qbraid==0.4.0"
]
requires-python = ">=3.7"

[project.optional-dependencies]
dev = ["black", "bumpver", "isort", "pip-tools", "pytest"]

[project.urls]
Homepage = "https://citynow.vn/"

