[build-system]
requires = ["setuptools>=61.0", "yfinance>=0.1.70", "plotly>=5.6.0", "pandas"]
build-backend = "setuptools.build_meta"

[project]
name = "quant23rg"
version = "0.0.1"
authors = [
  { name="Adrien Calas", email="le23rg@icloud.com" },
]
description = "Package for quantitative analysis"
readme = "README.md"
requires-python = ">=3.7"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]

[project.urls]
"Homepage" = "https://github.com/leRayGorbella/quant23rg"
"Bug Tracker" = "https://github.com/leRayGorbella/quant23rg/issues"