# pyproject.toml

[build-system]
requires      = ["setuptools>=61.0.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "neuralpit"
version = "1.0.12"
description = "NeuralPit SDK"
readme = "README.md"
authors = [{ name = "Quang Nguyen", email = "quang.nguyen@neuralpit.com" }]
license = { file = "LICENSE" }
classifiers = [
    "License :: OSI Approved :: MIT License",
    "Programming Language :: Python",
    "Programming Language :: Python :: 3",
]
keywords = ["api", "neural", "neuralpit"]
dependencies = [
    "requests",
    "lxml",
    "toml",
    "langchain==0.0.150",
    "openai",
    "tiktoken",
    "faiss-cpu==1.7.4",
    "bs4"
]
requires-python = ">=3.7"

[project.optional-dependencies]
dev = ["black", "bumpver", "isort", "pip-tools", "pytest"]

[tool.bumpver]
current_version = "2023.1001-alpha"
version_pattern = "YYYY.BUILD[-TAG]"
commit_message = "bump version {old_version} -> {new_version}"
commit = true
tag = true
push = true

[tool.bumpver.file_patterns]
"pyproject.toml" = ['current_version = "{version}"', 'version = "{version}"']
