[build-system]
requires = ["setuptools", "setuptools-scm"]
build-backend = "setuptools.build_meta"

[project]
name = "oneoneoneexample"
version = "0.2"

dependencies = [
  "pandas",
  "jinja2",
  "PyPDF2",
  "pdfkit"
]



