[tool.poetry]
name = "dmodel"
version = "0.0.2"
description = "models for deta space"
authors = ["Daniel Arantes <arantesdv@me.com>"]

[tool.poetry.dependencies]
python = "^3.9"
anyio = "^3.6.2"
typing-extensions = "^4.6.2"
dtbase = "^0.0.4"
dhint = "^0.0.8"
smartjs = "^0.1.6"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
