[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry]
name = "pingsafe_cli"
version = "0.0.3"
authors = ["pingsafe-dev <dev@pingsafe.com>"]
description = "PingSafe CLI is an extension of our vision to shift-left security with PingSafe."
readme = "README.md"
license = "Proprietary"

[tool.poetry.dependencies]
python = "^3.7.1"
jsonschema = "4.17.3"
requests = "2.29.0"
toml = "0.10.2"

[tool.poetry.scripts]
pre-build =  "pre_build.build_script:main"
pingsafe-cli = "pingsafe_cli.scanner.cli.main:start"